/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.ifsc.gerenciadorempresarial.gerenciadorempresarial;

import java.awt.event.ActionEvent;
import java.util.List;
import java.util.concurrent.Future;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/**
 *
 * @author ecama
 */
public class TelaSolicitaCompra extends javax.swing.JFrame {
        List<Produto> prods;
        List<Funcionario> funcs;
        
        
    public TelaSolicitaCompra() {
        initComponents();
        carregaProdutos();
        carregaFuncionarios();
        
    }
    
    public void carregaProdutos(){
        try{
            prods = Produto.buscaProdutos();
            if (prods.size() > 0){
                lblCod1.setText(String.valueOf(prods.get(0).getId()));
                lblDescr1.setText(prods.get(0).getNome());
                lblPreco1.setText("R$ " + prods.get(0).getPreco());
            }
            if (prods.size() > 1){
                lblCod2.setText(String.valueOf(prods.get(1).getId()));
                lblDescr2.setText(prods.get(1).getNome());
                lblPreco2.setText("R$ " + prods.get(1).getPreco());
            }
            if (prods.size() > 2){
                lblCod3.setText(String.valueOf(prods.get(2).getId()));
                lblDescr3.setText(prods.get(2).getNome());
                lblPreco3.setText("R$ " + prods.get(2).getPreco());
            }
            if (prods.size() > 3){
                lblCod4.setText(String.valueOf(prods.get(3).getId()));
                lblDescr4.setText(prods.get(3).getNome());
                lblPreco4.setText("R$ " + prods.get(3).getPreco());
            }
            if (prods.size() > 4){
                lblCod5.setText(String.valueOf(prods.get(4).getId()));
                lblDescr5.setText(prods.get(4).getNome());
                lblPreco5.setText("R$ " + prods.get(4).getPreco());
            }
            if (prods.size() > 5){
                lblCod6.setText(String.valueOf(prods.get(5).getId()));
                lblDescr6.setText(prods.get(5).getNome());
                lblPreco6.setText("R$ " + prods.get(5).getPreco());
            }
            if (prods.size() > 6){
                lblCod7.setText(String.valueOf(prods.get(6).getId()));
                lblDescr7.setText(prods.get(6).getNome());
                lblPreco7.setText("R$ " + prods.get(6).getPreco());
            }
            if (prods.size() > 7){
                lblCod8.setText(String.valueOf(prods.get(7).getId()));
                lblDescr8.setText(prods.get(7).getNome());
                lblPreco8.setText("R$ " + prods.get(7).getPreco());
            }
            if (prods.size() > 8){
                lblCod9.setText(String.valueOf(prods.get(8).getId()));
                lblDescr9.setText(prods.get(8).getNome());
                lblPreco9.setText("R$ " + prods.get(8).getPreco());
            }
            if (prods.size() > 9){
                lblCod10.setText(String.valueOf(prods.get(9).getId()));
                lblDescr10.setText(prods.get(9).getNome());
                lblPreco10.setText("R$ " + prods.get(9).getPreco());
            }
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, e.getMessage());
            System.exit(-1);
        }
                
    }
    public void carregaFuncionarios(){
        try{
            funcs = Funcionario.buscaFuncionarios();
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, e.getMessage());
            System.exit(-1);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        edtCodigo = new javax.swing.JTextField();
        lblProdSel = new javax.swing.JLabel();
        btnComprar = new javax.swing.JButton();
        edtCodigoSol = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        lblFuncSel = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lblCod1 = new javax.swing.JLabel();
        lblCod2 = new javax.swing.JLabel();
        lblCod3 = new javax.swing.JLabel();
        lblDescr1 = new javax.swing.JLabel();
        lblDescr2 = new javax.swing.JLabel();
        lblDescr3 = new javax.swing.JLabel();
        lblPreco1 = new javax.swing.JLabel();
        lblPreco2 = new javax.swing.JLabel();
        lblPreco3 = new javax.swing.JLabel();
        lblCod4 = new javax.swing.JLabel();
        lblDescr4 = new javax.swing.JLabel();
        lblPreco4 = new javax.swing.JLabel();
        lblCod5 = new javax.swing.JLabel();
        lblPreco5 = new javax.swing.JLabel();
        lblDescr5 = new javax.swing.JLabel();
        lblDescr6 = new javax.swing.JLabel();
        lblCod6 = new javax.swing.JLabel();
        lblPreco6 = new javax.swing.JLabel();
        lblCod7 = new javax.swing.JLabel();
        lblPreco7 = new javax.swing.JLabel();
        lblDescr7 = new javax.swing.JLabel();
        lblCod8 = new javax.swing.JLabel();
        lblDescr8 = new javax.swing.JLabel();
        lblPreco8 = new javax.swing.JLabel();
        lblPreco9 = new javax.swing.JLabel();
        lblDescr9 = new javax.swing.JLabel();
        lblCod9 = new javax.swing.JLabel();
        lblDescr10 = new javax.swing.JLabel();
        lblCod10 = new javax.swing.JLabel();
        lblPreco10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Solicitar Compra");
        setResizable(false);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Menu de Opções", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Microsoft Tai Le", 1, 14))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Digite o Código");

        edtCodigo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        edtCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edtCodigoActionPerformed(evt);
            }
        });
        edtCodigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                edtCodigoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                edtCodigoKeyTyped(evt);
            }
        });

        lblProdSel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        btnComprar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnComprar.setText("Comprar");
        btnComprar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComprarActionPerformed(evt);
            }
        });

        edtCodigoSol.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        edtCodigoSol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edtCodigoSolActionPerformed(evt);
            }
        });
        edtCodigoSol.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                edtCodigoSolKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                edtCodigoSolKeyTyped(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Código Solicitante");

        lblFuncSel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(edtCodigo)
                    .addComponent(btnComprar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(edtCodigoSol, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblFuncSel)
                            .addComponent(jLabel2)
                            .addComponent(lblProdSel)
                            .addComponent(jLabel3))
                        .addGap(0, 97, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(edtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblProdSel)
                .addGap(14, 14, 14)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(edtCodigoSol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblFuncSel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnComprar)
                .addGap(36, 36, 36))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Produtos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Microsoft Tai Le", 1, 14))); // NOI18N

        lblCod1.setText("lblCod1");

        lblCod2.setText("lblCod2");

        lblCod3.setText("lblCod3");

        lblDescr1.setText("lblDescr1");

        lblDescr2.setText("lblDescr2");

        lblDescr3.setText("lblDescr3");

        lblPreco1.setText("lblPreco1");

        lblPreco2.setText("lblPreco2");

        lblPreco3.setText("lblPreco3");

        lblCod4.setText("lblCod3");

        lblDescr4.setText("lblDescr3");

        lblPreco4.setText("lblPreco3");

        lblCod5.setText("lblCod3");

        lblPreco5.setText("lblPreco3");

        lblDescr5.setText("lblDescr3");

        lblDescr6.setText("lblDescr3");

        lblCod6.setText("lblCod3");

        lblPreco6.setText("lblPreco3");

        lblCod7.setText("lblCod3");

        lblPreco7.setText("lblPreco3");

        lblDescr7.setText("lblDescr3");

        lblCod8.setText("lblCod3");

        lblDescr8.setText("lblDescr3");

        lblPreco8.setText("lblPreco3");

        lblPreco9.setText("lblPreco3");

        lblDescr9.setText("lblDescr3");

        lblCod9.setText("lblCod3");

        lblDescr10.setText("lblDescr3");

        lblCod10.setText("lblCod3");

        lblPreco10.setText("lblPreco3");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCod1)
                    .addComponent(lblCod2)
                    .addComponent(lblCod3)
                    .addComponent(lblCod4)
                    .addComponent(lblCod5)
                    .addComponent(lblCod6)
                    .addComponent(lblCod7)
                    .addComponent(lblCod8)
                    .addComponent(lblCod9)
                    .addComponent(lblCod10))
                .addGap(68, 68, 68)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDescr1)
                    .addComponent(lblDescr2)
                    .addComponent(lblDescr3)
                    .addComponent(lblDescr4)
                    .addComponent(lblDescr5)
                    .addComponent(lblDescr6)
                    .addComponent(lblDescr7)
                    .addComponent(lblDescr8)
                    .addComponent(lblDescr9)
                    .addComponent(lblDescr10))
                .addGap(68, 68, 68)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPreco3)
                    .addComponent(lblPreco2)
                    .addComponent(lblPreco1)
                    .addComponent(lblPreco4)
                    .addComponent(lblPreco5)
                    .addComponent(lblPreco6)
                    .addComponent(lblPreco7)
                    .addComponent(lblPreco8)
                    .addComponent(lblPreco9)
                    .addComponent(lblPreco10))
                .addContainerGap(56, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCod1)
                    .addComponent(lblDescr1)
                    .addComponent(lblPreco1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCod2)
                    .addComponent(lblDescr2)
                    .addComponent(lblPreco2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCod3)
                    .addComponent(lblDescr3)
                    .addComponent(lblPreco3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCod4)
                    .addComponent(lblDescr4)
                    .addComponent(lblPreco4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCod5)
                    .addComponent(lblDescr5)
                    .addComponent(lblPreco5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCod6)
                    .addComponent(lblDescr6)
                    .addComponent(lblPreco6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCod7)
                    .addComponent(lblDescr7)
                    .addComponent(lblPreco7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCod8)
                    .addComponent(lblDescr8)
                    .addComponent(lblPreco8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCod9)
                    .addComponent(lblDescr9)
                    .addComponent(lblPreco9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCod10)
                    .addComponent(lblDescr10)
                    .addComponent(lblPreco10))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 12, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void edtCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edtCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edtCodigoActionPerformed

    private void edtCodigoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_edtCodigoKeyReleased
        String cod = edtCodigo.getText();
        String nome = "";
        if(cod.length() > 0){
            Integer codProd = Integer.parseInt(cod);

            for(Produto p : prods){
                if(p.getId() == codProd){
                    nome = p.getNome();
                }
            }
            lblProdSel.setText(nome);
        }
    }//GEN-LAST:event_edtCodigoKeyReleased

    private void edtCodigoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_edtCodigoKeyTyped
        char key = evt.getKeyChar();
        if(key < 48 || key > 57){
            evt.consume();
        }
    }//GEN-LAST:event_edtCodigoKeyTyped

    private void btnComprarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComprarActionPerformed
        String codProd = edtCodigo.getText();
        String codFunc = edtCodigoSol.getText();
        Integer cod = -1;
        Integer codf = -1;
        Object sel;
        Produto prod = null;
        Funcionario func = null;

        if (codProd.length() > 0) {
            cod = Integer.parseInt(codProd);
        } else {
            JOptionPane.showMessageDialog(this, "Você deve informar um Produto");
            return;
        }
        if (codFunc.length() > 0) {
            codf = Integer.parseInt(codFunc);
        } else {
            JOptionPane.showMessageDialog(this, "Você deve informar um Solicitante");
            return;
        }

        for (Produto p : prods) {
            if (p.getId() == cod) {
                prod = p;
            }
        }
        for (Funcionario f : funcs){
            if (f.getId() == codf) {
                func = f;
            }
        }

        if (prod == null) {
            JOptionPane.showMessageDialog(this, "Produto inválido!");
            return;
        }
        if (func == null) {
            JOptionPane.showMessageDialog(this, "Funcionário inválido!");
            return;
        }
        

            Compra reg = new Compra(prod.getPreco(), func, prod);
            try {
                reg.salvar();
            } catch (Exception ex) {
                ex.printStackTrace();
                JOptionPane.showMessageDialog(this,
                    ex.getMessage());
                return;
            }

            JOptionPane.showMessageDialog(this,
                "Venda confirmada! Retire seu produto.");
        
    }//GEN-LAST:event_btnComprarActionPerformed

    private void edtCodigoSolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edtCodigoSolActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edtCodigoSolActionPerformed

    private void edtCodigoSolKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_edtCodigoSolKeyReleased
        String codF = edtCodigoSol.getText();
        String nomeF = "";
        if(codF.length() > 0){
            Integer codSol = Integer.parseInt(codF);

            for(Funcionario f : funcs){
                if(f.getId() == codSol){
                    nomeF = f.getNome();
                }
            }
            lblFuncSel.setText(nomeF);
        }
    }//GEN-LAST:event_edtCodigoSolKeyReleased

    private void edtCodigoSolKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_edtCodigoSolKeyTyped
        char key = evt.getKeyChar();
        if(key < 48 || key > 57){
            evt.consume();
        }
    }//GEN-LAST:event_edtCodigoSolKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaSolicitaCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaSolicitaCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaSolicitaCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaSolicitaCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaSolicitaCompra().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnComprar;
    private javax.swing.JTextField edtCodigo;
    private javax.swing.JTextField edtCodigoSol;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblCod1;
    private javax.swing.JLabel lblCod10;
    private javax.swing.JLabel lblCod2;
    private javax.swing.JLabel lblCod3;
    private javax.swing.JLabel lblCod4;
    private javax.swing.JLabel lblCod5;
    private javax.swing.JLabel lblCod6;
    private javax.swing.JLabel lblCod7;
    private javax.swing.JLabel lblCod8;
    private javax.swing.JLabel lblCod9;
    private javax.swing.JLabel lblDescr1;
    private javax.swing.JLabel lblDescr10;
    private javax.swing.JLabel lblDescr2;
    private javax.swing.JLabel lblDescr3;
    private javax.swing.JLabel lblDescr4;
    private javax.swing.JLabel lblDescr5;
    private javax.swing.JLabel lblDescr6;
    private javax.swing.JLabel lblDescr7;
    private javax.swing.JLabel lblDescr8;
    private javax.swing.JLabel lblDescr9;
    private javax.swing.JLabel lblFuncSel;
    private javax.swing.JLabel lblPreco1;
    private javax.swing.JLabel lblPreco10;
    private javax.swing.JLabel lblPreco2;
    private javax.swing.JLabel lblPreco3;
    private javax.swing.JLabel lblPreco4;
    private javax.swing.JLabel lblPreco5;
    private javax.swing.JLabel lblPreco6;
    private javax.swing.JLabel lblPreco7;
    private javax.swing.JLabel lblPreco8;
    private javax.swing.JLabel lblPreco9;
    private javax.swing.JLabel lblProdSel;
    // End of variables declaration//GEN-END:variables
}
